name: .conda
channels:
  - conda-forge
  - pypi
  - defaults
dependencies:
  - python=3.10
  - pytest
  - types-requests
  - types-pynput
  - mypy
  - python-dotenv
  - rich
  - anthropic
  - openai
  - ffmpeg
  - soundfile
  - sounddevice
  - scipy
  - alsa-lib
  - python-sounddevice
  - numpy
  - pynput
  - graphviz
  - pygraphviz
  - playwright