name: .conda
channels:
  - conda-forge
  - pypi
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest
  - types-requests
  - mypy
  - python-dotenv
  - rich
  - anthropic
  - openai
  - ffmpeg
  - scipy
  - alsa-lib
  - python-sounddevice
  - numpy
  - pynput
  - graphviz
  - pygraphviz
  - playwright
  - backoff
  - pip:
    - types-pynput
    - soundfile
    - sounddevice
    - playwright