import sys
import dotenv

from rich import print

from agents.state_callback import StateCallback

dotenv.load_dotenv()


## Begin code generated by meta_tools/update_callbacks.py


class root_Callback(StateCallback):
    def on_enter(self, csm, locals):
        print(f"{self.PRINT_PREFIX} Entering root")
        # Perform actions when entering root
        pass

    def on_exit(self, csm, locals):
        print(f"{self.PRINT_PREFIX} Exiting root")
        # Perform actions when exiting root
        pass

class PrintUIMessage_Callback(StateCallback):
    def on_enter(self, csm, locals):
        print(f"{self.PRINT_PREFIX} Entering PrintUIMessage")
        # Perform actions when entering PrintUIMessage
        pass

    def on_exit(self, csm, locals):
        print(f"{self.PRINT_PREFIX} Exiting PrintUIMessage")
        # Perform actions when exiting PrintUIMessage
        pass

class AssignAction_Callback(StateCallback):
    def on_enter(self, csm, locals):
        print(f"{self.PRINT_PREFIX} Entering AssignAction")
        # Perform actions when entering AssignAction

        prior_state = csm.state_history[-1]
        agent_manager = locals["self"].agent_manager

        # Should always be True
        if prior_state.action:
            print(f"{self.PRINT_PREFIX} prior_state.action: {prior_state.action}")
            agent_manager.route_action(prior_state.action)
            csm.transition("epsilon", {})
        else:
            print(f"[red][bold]{self.PRINT_PREFIX} prior_state {prior_state.get_hpath()} did not have an action[/bold][/red]")
            sys.exit(1)
        

    def on_exit(self, csm, locals):
        print(f"{self.PRINT_PREFIX} Exiting AssignAction")
        # Perform actions when exiting AssignAction
        pass

class Exit_Callback(StateCallback):
    def on_enter(self, csm, locals):
        print(f"{self.PRINT_PREFIX} Entering Exit")
        # Perform actions when entering Exit
        pass

    def on_exit(self, csm, locals):
        print(f"{self.PRINT_PREFIX} Exiting Exit")
        # Perform actions when exiting Exit
        pass
